[package]
name = "fulgur-raikiri"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Raikiri layout backend under development for fulgur"
readme = "README.md"

[dependencies]
krilla = "0.7.0"
fulgur-core = { path = "../fulgur-core" }
raikiri-html = { git = "https://github.com/fulgur-rs/raikiri.git", rev = "c817e0e97af841ee02aa2352b40350304a789d11" }
raikiri-traits = { git = "https://github.com/fulgur-rs/raikiri.git", rev = "c817e0e97af841ee02aa2352b40350304a789d11" }
url = "2.5"

[dev-dependencies]
tempfile = "3"
lopdf = "0.42"
