[package]
name = "fulgur-raikiri"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Raikiri layout backend under development for fulgur"
readme = "README.md"

[dependencies]
krilla = "0.7.0"
skrifa = "0.45"
fulgur-core = { path = "../fulgur-core" }
raikiri-html = { git = "https://github.com/fulgur-rs/raikiri.git", rev = "8123161eae1e2884d0f8535fbcef65f8625d0e9d" }
raikiri-traits = { git = "https://github.com/fulgur-rs/raikiri.git", rev = "8123161eae1e2884d0f8535fbcef65f8625d0e9d" }
url = "2.5"
percent-encoding = "2"

[dev-dependencies]
tempfile = "3"
lopdf = "0.42"
