[package]
name = "fulgur-raikiri"
version = "0.40.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Raikiri layout backend under development for fulgur"
readme = "README.md"

[dependencies]
fulgur-core = { version = "0.40.0", path = "../fulgur-core" }
raikiri-html = { git = "https://github.com/fulgur-rs/raikiri.git", rev = "52f1dc81ac581ea465e6059df5dd8223f56b2db8" }

[dev-dependencies]
tempfile = "3"
raikiri-traits = { git = "https://github.com/fulgur-rs/raikiri.git", rev = "52f1dc81ac581ea465e6059df5dd8223f56b2db8" }
