"""Type stubs for pyfulgur.

Docstrings are intentionally omitted here — the canonical source is the Rust
``///`` doc comments, which PyO3 surfaces as ``__doc__`` at runtime. griffe
(mkdocstrings) and modern IDEs merge ``.pyi`` types with runtime docstrings
automatically.
"""

import os
from typing import List, Optional, Union

__version__: str
__all__: List[str]


class RenderError(Exception): ...


class PageSize:
    A4: PageSize
    LETTER: PageSize
    A3: PageSize

    @staticmethod
    def custom(width_mm: float, height_mm: float) -> PageSize: ...
    def landscape(self) -> PageSize: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def __repr__(self) -> str: ...


class Margin:
    def __init__(
        self,
        top: float,
        right: float,
        bottom: float,
        left: float,
    ) -> None: ...
    @staticmethod
    def uniform(pt: float) -> Margin: ...
    @staticmethod
    def symmetric(vertical: float, horizontal: float) -> Margin: ...
    @staticmethod
    def uniform_mm(mm: float) -> Margin: ...
    @property
    def top(self) -> float: ...
    @property
    def right(self) -> float: ...
    @property
    def bottom(self) -> float: ...
    @property
    def left(self) -> float: ...
    def __repr__(self) -> str: ...


class AssetBundle:
    def __init__(self) -> None: ...
    def add_css(self, css: str) -> None: ...
    def add_css_file(self, path: Union[str, "os.PathLike[str]"]) -> None: ...
    def add_font_file(self, path: Union[str, "os.PathLike[str]"]) -> None: ...
    def add_image(self, name: str, data: bytes) -> None: ...
    def add_image_file(
        self, name: str, path: Union[str, "os.PathLike[str]"]
    ) -> None: ...


class EngineBuilder:
    def __init__(self) -> None: ...
    def page_size(self, value: Union[PageSize, str]) -> EngineBuilder: ...
    def margin(self, margin: Margin) -> EngineBuilder: ...
    def landscape(self, value: bool) -> EngineBuilder: ...
    def title(self, value: str) -> EngineBuilder: ...
    def author(self, value: str) -> EngineBuilder: ...
    def lang(self, value: str) -> EngineBuilder: ...
    def bookmarks(self, value: bool) -> EngineBuilder: ...
    def assets(self, bundle: AssetBundle) -> EngineBuilder: ...
    def build(self) -> Engine: ...


class Engine:
    def __init__(
        self,
        *,
        page_size: Optional[Union[PageSize, str]] = ...,
        margin: Optional[Margin] = ...,
        landscape: Optional[bool] = ...,
        title: Optional[str] = ...,
        author: Optional[str] = ...,
        lang: Optional[str] = ...,
        bookmarks: Optional[bool] = ...,
        assets: Optional[AssetBundle] = ...,
    ) -> None: ...
    @staticmethod
    def builder() -> EngineBuilder: ...
    def render_html(self, html: str) -> bytes: ...
    def render_html_to_file(
        self, html: str, path: Union[str, "os.PathLike[str]"]
    ) -> None: ...
